[manifest]
version = "1.0.0"
dump_lua = true
priority = -1


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "sliced_card.getting_sliced = true"
position = "after"
payload = '''
G.hasajokerbeendestroyedthistick_unused = true
'''
match_indent = false



# calculate wheel fail (for Freaky)

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Ectoplasm' or self.ability.name == 'Hex' or pseudorandom('wheel_of_fortune') < G.GAME.probabilities.normal/self.ability.extra then"
position = "before"
match_indent = true
payload = '''
if self.ability.name == 'The Wheel of Fortune' then
    self.cry_wheel_success = false
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Ectoplasm' or self.ability.name == 'Hex' or pseudorandom('wheel_of_fortune') < G.GAME.probabilities.normal/self.ability.extra then"
position = "after"
match_indent = true
payload = '''
if self.ability.name == 'The Wheel of Fortune' then
    self.cry_wheel_success = true
end
'''

