[manifest]
version = "1.0.0"
dump_lua = true
priority = -1


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "sliced_card.getting_sliced = true"
position = "after"
payload = '''
G.hasajokerbeendestroyedthistick_unused = true
'''
match_indent = false



# wheel flag (more robust)

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "pseudorandom('wheel_of_fortune')"
position = "before"
match_indent = false
payload = '''
if self.ability and self.ability.name == 'The Wheel of Fortune' then
    self.cry_wheel_success = false
end
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "pseudorandom('wheel_of_fortune')"
position = "after"
match_indent = false
payload = '''
if self.ability and self.ability.name == 'The Wheel of Fortune' then
    self.cry_wheel_success = true
end
'''


